name: CI

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

env:
    hash: $(git rev-parse --short=8 "$GITHUB_SHA")
    branch: $(echo ${GITHUB_REF_NAME/\//-})

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

        - uses: actions/checkout@v4

        - name: Hash
          run: echo ${{ env.hash }}

        - name: Hash
          run: echo ${{ env.branch }}
            