name: CI

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

env:
    hash: $(git rev-parse --short=8 "$GITHUB_SHA")
    branch: $(echo ${GITHUB_REF_NAME/\//-})

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

        - uses: actions/checkout@v4

        - name: Set globals
          id: globals
          shell: bash
          run: |
            echo "HASH=${{ env.hash }}" >> "${GITHUB_OUTPUT}"
            echo "BRANCH=${{ env.branch }}" >> "${GITHUB_OUTPUT}"

        - name: Hash
          run: echo ${{ env.hash }}

        - name: Branch
          run: echo ${{ env.branch }}
            
        - name: Globals
          run: echo ${{ steps.globals.outputs.HASH }}
            