name: CI

on:
    push:
        branches:
            - main
            - feature/*
            
env:
    hash: $(git rev-parse --short=8 "$GITHUB_SHA")
    branch: ${GITHUB_REF_NAME/\//-}

jobs:

    build:

        runs-on: ubuntu-latest

        steps:

        - uses: actions/checkout@v4

        - name: Hash
          run: echo ${{ env.hash }}

        - name: Hash
          run: echo ${{ env.branch }}
            